- name: Create vagrantfile directory
  sudo: no
  file:
    path: '~/test-env'
    state: directory
    mode: 0755

- name: Copy Vagrantfile
sudo: no
  copy: 
    src: Vagrantfile
    dest: '~/test-env/Vagrantfile'

- name: Copy provision file using Vagrantfile
  sudo: no
  copy: 
    src: setup-vagrant.yml
    dest: '~/test-env/setup-vagrant.yml'
