- name: Upstart etherpad conf
  copy: src=upstart.conf dest=/etc/init/etherpad.conf

- name: Create etherpad plugins directory
  file:
    path: /volumes/etherpad/data/plugins
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create etherpad database
  docker:
    name: create-etherpad-database
    image: mysql
    links: mysql-container:mysql
    detach: False
    command: >
      sh -c 'exec echo "create database if not exists etherpad DEFAULT CHARACTER SET utf8" |
      mysql -h"$MYSQL_PORT_3306_TCP_ADDR"
      -P"$MYSQL_PORT_3306_TCP_PORT"
      -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'

- name: etherpad container
  docker:
    name: etherpad-container
    links: mysql-container:mysql
    image: tvelocity/etherpad-lite
    ports: "{{ etherpad_port }}:9001"
  notify: Start etherpad container

- name: etherpad site
  template:
    src: site.conf
    dest: /volumes/etc/nginx/sites-enabled/etherpad.conf
  notify: Restart Nginx container
