- name: Add no_proxy to /etc/environment
  sudo: yes
  lineinfile:
    create: yes
    dest: '/etc/environment'
    state: present
    line: 'export no_proxy={{ proxy.no_proxy }}'
  when: proxy.no_proxy | default(False)

- name: Add http_proxy to /etc/environment
  sudo: yes
  lineinfile:
    create: yes
    dest: '/etc/environment'
    state: present
    line: 'export http_proxy={{ proxy.http_proxy }}'
  when: proxy.http_proxy | default(False)

- name: Remove http_proxy to /etc/environment
  sudo: yes
  lineinfile:
    dest: '/etc/environment'
    state: absent
    regexp: "^export\\s+http_proxy\\=.*"
  when: proxy.http_proxy == False

- name: Add https_proxy to /etc/environment
  sudo: yes
  lineinfile:
    create: yes
    dest: '/etc/environment'
    state: present
    line: 'export https_proxy={{ proxy.https_proxy }}'
  when: proxy.https_proxy | default(False)

- name: Remove https_proxy to /etc/environment
  sudo: yes
  lineinfile:
    dest: '/etc/environment'
    state: absent
    regexp: "^export\\s+https_proxy\\=.*"
  when: proxy.https_proxy == False